// All reusable variables here
#let myLang = "it"
#let myName = "Matteo Rango"
#let myMatricola = "2008066"
#let myTitle = "Modernizzazione delle Applicazioni dei Sistemi di Controllo"
#let myDegree = "Tesi di laurea"
#let myUni = "Università degli Studi di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof. "
#let myProf = "Tullio Vardanega"
#let myCompany = "Bluewind S.R.L."
#let myTutor = "Alessio Gobbo"
#let myLocation = "Padova"
#let myAA = "2023-2024"
#let myTime = "Settembre 2024"
